# Generated by Django 4.0.1 on 2022-01-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='typ_receita',
            field=models.CharField(choices=[('s', 'salário'), ('p', 'prêmio,'), ('o', 'outros')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_conta', to='main.conta'),
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dPagamento', models.DateField()),
                ('dPa_Esperado', models.DateField()),
                ('desc', models.TextField()),
                ('typ_despesa', models.CharField(choices=[('a', 'alimentação'), ('e', 'educação'), ('l', 'lazer'), ('m', 'moradia'), ('r', 'roupa'), ('s', 'saúde'), ('t', 'transporte'), ('o', 'outros')], max_length=2)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='D_conta', to='main.conta')),
            ],
        ),
    ]
