# Generated by Django 4.0.1 on 2022-01-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_receitas_typ_receita_alter_receitas_conta_despesas'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='titular',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
